### ISSUE TITLE
TTEX Beta 0.3.1 config untouched

### ISSUE THREAD

**Issue by momfertje** [DCC-EX/Turntable-EX#77]
### Testing configuration

* CommandStation-EX version: 4.0.2 (add-turntable-controller version)
* Turntable-EX version: 0.3.1 Beta
* Microcontroller: Nano V3
* Stepper driver: ULN2003
* Stepper motor: 28BYJ-48
* Homing sensor: A3144
* Dual relay board: Active Low

`If you have edited config.h in Turntable-EX or myHalcpp or myAutomation.h in CommandStation-EX, please upload those to this issue also.`

### Test 1 - Startup Sequence

`PASS`

Any observations or comments:

### Test 2 - Turntable-EX is Available

`PASS`

Any observations or comments:

#### Test 3, Part 1 - Clockwise

`PASS`

Any observations or comments:

#### Test 3, Part 2 - Counter Clockwise

`PASS`

Any observations or comments:

### Test 4 - Homing

`PASS`

Any observations or comments:

### Test 5 - Calibration

`PASS`

Any observations or comments:

### Test 6 - LED Output Testing

`PASS`

Any observations or comments:

### Test 7 - Accessory Output Testing

`PASS`

Any observations or comments:

### Test 8 - Manual Phase Switching

`PASS`

Any observations or comments:

### General comments or feedback

Please share any general comments or feedback here:

**Testing switch moment (calibrated at 4100 half step modus):**
`
Phase will switch at 495 steps from home, and revert at 2475 steps from home
Turntable homed successfully
Received notification to move to step postion 494
Position steps: 494, Auto phase switch - moving 494 steps
Setting phase switch flag to: 0
Received notification to move to step postion 495
Position steps: 495, Auto phase switch - moving 1 steps
`

**Comment by peteGSX** [comment]
Looks like all passed as expected.
